import { NSP_INCOGNITO_DATA } from 'app/consts';

export const KEY_REDUCER_INCOGNITO = 'incognitoDataReducer';
export const INCOGNITO_GET_ACCOUNTS = `${NSP_INCOGNITO_DATA}INCOGNITO_GET_ACCOUNTS`;
export const INCOGNITO_GET_ACCOUNTS_SUCCEEDED = `${NSP_INCOGNITO_DATA}INCOGNITO_GET_ACCOUNTS_SUCCEEDED`;
export const INCOGNITO_ACCOUNT_SELECTED = `${NSP_INCOGNITO_DATA}INCOGNITO_ACCOUNT_SELECTED`;
export const INCOGNITO_CREATE_ACCOUNT = `${NSP_INCOGNITO_DATA}INCOGNITO_CREATE_ACCOUNT`;
export const INCOGNITO_REMOVE_ACCOUNT = `${NSP_INCOGNITO_DATA}INCOGNITO_REMOVE_ACCOUNT`;
export const INCOGNITO_REMOVE_ERROR = `${NSP_INCOGNITO_DATA}INCOGNITO_REMOVE_ERROR`;

export const FIELDS_STATE = {
    ACCOUNTS: 'ACCOUNTS',
    ACCOUNT_SELECTED: 'ACCOUNT_SELECTED',
    INCOGNITO_ERROR: 'INCOGNITO_ERROR',
    INCOGNITO_LOADING: 'INCOGNITO_LOADING',
};
