import { NSP_INCOGNITO_DATA } from 'app/consts';
export const KEY_REDUCER_INCOGNITO = 'IncognitoDataReducer';

export const INCOGNITO_INIT = `${NSP_INCOGNITO_DATA}INCOGNITO_INIT`;
export const INCOGNITO_INIT_SUCCESSED = `${NSP_INCOGNITO_DATA}INCOGNITO_INIT_SUCCESSED`;
export const INCOGNITO_INIT_FAILED = `${NSP_INCOGNITO_DATA}INCOGNITO_INIT_FAILED`;

export const FIELDS_STATE = {
    WALLET: 'WALLET',
    MASTER_ACCOUNT: 'MASTER_ACCOUNT',
    INCOGNITO_LOADING: 'INCOGNITO_LOADING',
    INCOGNITO_ERROR: 'INCOGNITO_ERROR',
};
