import { NSP_INCOGNITO_DATA } from 'app/consts';

export const KEY_REDUCER_INCOGNITO = 'incognitoDataReducer';
export const INCOGNITO_LOAD_WALLET = `${NSP_INCOGNITO_DATA}INCOGNITO_LOAD_WALLET`;
export const INCOGNITO_CREATE_WALLET = `${NSP_INCOGNITO_DATA}INCOGNITO_CREATE_WALLET`;
export const INCOGNITO_LOAD_WALLET_SUCCEEDED = `${NSP_INCOGNITO_DATA}INCOGNITO_LOAD_WALLET_SUCCEEDED`;
export const INCOGNITO_LOAD_WALLET_FAILED = `${NSP_INCOGNITO_DATA}INCOGNITO_LOAD_WALLET_FAILED`;
export const INCOGNITO_ACCOUNT_SELECTED = `${NSP_INCOGNITO_DATA}INCOGNITO_ACCOUNT_SELECTED`;

export const FIELDS_STATE = {
    WALLET: 'WALLET',
    MASTER_ACCOUNT: 'MASTER_ACCOUNT',
    INCOGNITO_LOADING: 'INCOGNITO_LOADING',
    INCOGNITO_ERROR: 'INCOGNITO_ERROR',
    ACCOUNT_SELECTED: 'ACCOUNT_SELECTED',
};
